package tampilan;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import koneksi.Koneksi;
import koneksi.Sesi;

/**
 *
 * @author muham_000
 */
public class MenuLogin extends javax.swing.JFrame {

    //deklarasi class koneksi
    Connection conn = new Koneksi().connect();
    protected int id_karyawan;
    
    //deklarasi posisi mouse
    private int xMouse, yMouse;

    // method menampilkan password
    void tampilkanSandi() {
        if (cTampilkanSandi.isSelected()) {
            tKataSandi.setEchoChar((char) 0);
        } else {
            tKataSandi.setEchoChar('*');
        }
    }

    protected void login() {
        try {
            MenuUtama menuUtama = new MenuUtama();
            String query = "SELECT * FROM karyawan where nama_karyawan=? AND kata_sandi=?";
            PreparedStatement pst = conn.prepareStatement(query);
            pst.setString(1, tNamaPengguna.getText());
            pst.setString(2, tKataSandi.getText());
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                String role = rs.getString("role");
                Sesi.setIDLogin(rs.getInt("id_karyawan"));
                Sesi.setRole(role);

                if (role.equalsIgnoreCase("admin")) {
                    JOptionPane.showMessageDialog(null, "Selamat datang Admin");
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Selamat datang User");
                    dispose();
                }

                menuUtama.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Nama Pengguna atau Kata Sandi Salah");
            }

            rs.close();
            pst.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    /**
     * Creates new form MenuLogin
     */
    public MenuLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundLogin2 = new tampilan.BackgroundLogin();
        lIconLaundry = new javax.swing.JLabel();
        lNamaPengguna = new javax.swing.JLabel();
        lKataSandi = new javax.swing.JLabel();
        tNamaPengguna = new javax.swing.JTextField();
        tKataSandi = new javax.swing.JPasswordField();
        bMasuk = new javax.swing.JButton();
        cTampilkanSandi = new javax.swing.JCheckBox();
        lExit = new javax.swing.JLabel();
        lMinimize = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        setUndecorated(true);

        backgroundLogin2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                backgroundLogin2MouseDragged(evt);
            }
        });
        backgroundLogin2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backgroundLogin2MousePressed(evt);
            }
        });

        lIconLaundry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/p.png"))); // NOI18N

        lNamaPengguna.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lNamaPengguna.setForeground(new java.awt.Color(255, 255, 255));
        lNamaPengguna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/outline_account_circle_white_36dp.png"))); // NOI18N
        lNamaPengguna.setText("Nama Pengguna :");

        lKataSandi.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lKataSandi.setForeground(new java.awt.Color(255, 255, 255));
        lKataSandi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/outline_lock_white_36dp.png"))); // NOI18N
        lKataSandi.setText("Kata Sandi :");

        tNamaPengguna.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tNamaPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNamaPenggunaActionPerformed(evt);
            }
        });

        bMasuk.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        bMasuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/outline_login_black_36dp.png"))); // NOI18N
        bMasuk.setText("MASUK");
        bMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMasukActionPerformed(evt);
            }
        });

        cTampilkanSandi.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cTampilkanSandi.setForeground(new java.awt.Color(255, 255, 255));
        cTampilkanSandi.setText("Tampilkan Sandi");
        cTampilkanSandi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTampilkanSandiActionPerformed(evt);
            }
        });

        lExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/outline_close_white_24dp.png"))); // NOI18N
        lExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lExitMouseClicked(evt);
            }
        });

        lMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/outline_minimize_white_24dp.png"))); // NOI18N
        lMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lMinimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout backgroundLogin2Layout = new javax.swing.GroupLayout(backgroundLogin2);
        backgroundLogin2.setLayout(backgroundLogin2Layout);
        backgroundLogin2Layout.setHorizontalGroup(
            backgroundLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLogin2Layout.createSequentialGroup()
                .addContainerGap(241, Short.MAX_VALUE)
                .addGroup(backgroundLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLogin2Layout.createSequentialGroup()
                        .addComponent(bMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(316, 316, 316))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLogin2Layout.createSequentialGroup()
                        .addComponent(lIconLaundry, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(297, 297, 297))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLogin2Layout.createSequentialGroup()
                        .addGroup(backgroundLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lKataSandi)
                            .addGroup(backgroundLogin2Layout.createSequentialGroup()
                                .addComponent(lNamaPengguna)
                                .addGap(40, 40, 40)
                                .addGroup(backgroundLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tKataSandi, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(tNamaPengguna))))
                        .addGap(27, 27, 27)
                        .addComponent(cTampilkanSandi)
                        .addGap(121, 121, 121))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLogin2Layout.createSequentialGroup()
                        .addComponent(lMinimize)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lExit)
                        .addContainerGap())))
        );

        backgroundLogin2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lKataSandi, lNamaPengguna, tKataSandi, tNamaPengguna});

        backgroundLogin2Layout.setVerticalGroup(
            backgroundLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLogin2Layout.createSequentialGroup()
                .addGroup(backgroundLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lMinimize)
                    .addComponent(lExit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lIconLaundry, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(backgroundLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lNamaPengguna)
                    .addComponent(tNamaPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(backgroundLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lKataSandi)
                    .addComponent(tKataSandi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cTampilkanSandi))
                .addGap(42, 42, 42)
                .addComponent(bMasuk)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        backgroundLogin2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lKataSandi, lNamaPengguna, tKataSandi, tNamaPengguna});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundLogin2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundLogin2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMasukActionPerformed
        login();
    }//GEN-LAST:event_bMasukActionPerformed

    private void cTampilkanSandiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTampilkanSandiActionPerformed
        tampilkanSandi();
    }//GEN-LAST:event_cTampilkanSandiActionPerformed

    private void lExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lExitMouseClicked

    private void lMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lMinimizeMouseClicked
        this.setExtendedState(JFrame.ICONIFIED);

    }//GEN-LAST:event_lMinimizeMouseClicked

    private void backgroundLogin2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundLogin2MousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_backgroundLogin2MousePressed

    private void backgroundLogin2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundLogin2MouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_backgroundLogin2MouseDragged

    private void tNamaPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNamaPenggunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNamaPenggunaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bMasuk;
    private tampilan.BackgroundLogin backgroundLogin2;
    private javax.swing.JCheckBox cTampilkanSandi;
    private javax.swing.JLabel lExit;
    private javax.swing.JLabel lIconLaundry;
    private javax.swing.JLabel lKataSandi;
    private javax.swing.JLabel lMinimize;
    private javax.swing.JLabel lNamaPengguna;
    private javax.swing.JPasswordField tKataSandi;
    private javax.swing.JTextField tNamaPengguna;
    // End of variables declaration//GEN-END:variables
}
