package tampilan;

import java.sql.Connection;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import koneksi.Koneksi;
import koneksi.Sesi;

/**
 *
 * @author muham_000
 */
public class MenuUtama extends javax.swing.JFrame {

    //deklarasi class koneksi
    Connection conn = new Koneksi().connect();
    int choice;
    
    //deklarasi posisi mouse
    private int xMouse, yMouse;

    protected void keluar(){
        choice = JOptionPane.showConfirmDialog(null, "Apakah Anda Ingin Keluar ?", "Keluar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null);
        if (choice == 0){
        MenuLogin menuLogin = new MenuLogin();
        menuLogin.setVisible(true);
        dispose();
        }
    }
    
    protected void menuTransaksi(){
          MenuTransaksi menuTransaksi = new MenuTransaksi();
          menuTransaksi.setVisible(true);
          dispose();
    }
    
    protected void menuPelanggan(){
        MenuPelanggan menuPelanggan = new MenuPelanggan();
        menuPelanggan.setVisible(true);
        dispose();
    }
    
    protected void menuKaryawan(){
        String role = Sesi.getRole();
        if(role.equals("Admin") == true){
            MenuKaryawanUntukAdmin menuKaryawanUntukAdmin = new MenuKaryawanUntukAdmin();
            menuKaryawanUntukAdmin.setVisible(true);
            dispose();
        } else if(role.equals("User") == true){
            MenuKaryawanUntukUser menuKaryawanUntukUser = new MenuKaryawanUntukUser();
            menuKaryawanUntukUser.setVisible(true);
            dispose();
        }
    }
    
    protected  void menuLayanan(){
        MenuLayanan menuLayanan = new MenuLayanan();
        menuLayanan.setVisible(true);
        dispose();
    }
    
    protected void menuPengambilan(){
        MenuPengambilan menuPengambilan = new MenuPengambilan();
        menuPengambilan.setVisible(true);
        dispose();
    }
    
    protected void menuKomplain(){
        MenuKomplain menuKomplain = new MenuKomplain();
        menuKomplain.setVisible(true);
        dispose();
    }
    
    protected void menuLaporan(){
        MenuLaporan menuLaporan = new MenuLaporan();
        menuLaporan.setVisible(true);
        dispose();
    }
    
    /**
     * Creates new form MenuLogin
     */
    public MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        lIconLaundry = new javax.swing.JLabel();
        lExit = new javax.swing.JLabel();
        lMinimize = new javax.swing.JLabel();
        Body = new javax.swing.JPanel();
        bTransaksi = new javax.swing.JButton();
        bPengambilan = new javax.swing.JButton();
        bKomplain = new javax.swing.JButton();
        bPelanggan = new javax.swing.JButton();
        bLayanan = new javax.swing.JButton();
        bKaryawan = new javax.swing.JButton();
        bLaporan = new javax.swing.JButton();
        bKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);

        Header.setBackground(new java.awt.Color(50, 126, 172));
        Header.setPreferredSize(new java.awt.Dimension(800, 200));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        lIconLaundry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/p.png"))); // NOI18N

        lExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/outline_close_white_24dp.png"))); // NOI18N
        lExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lExitMouseClicked(evt);
            }
        });

        lMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/outline_minimize_white_24dp.png"))); // NOI18N
        lMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lMinimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(lIconLaundry)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lMinimize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lExit)
                .addContainerGap())
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lIconLaundry, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lMinimize)
                    .addComponent(lExit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Body.setBackground(new java.awt.Color(131, 187, 230));

        bTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pay_cash_payment_money_dollar_bill_icon_143267.png"))); // NOI18N
        bTransaksi.setText("TRANSAKSI");
        bTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTransaksiActionPerformed(evt);
            }
        });

        bPengambilan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bPengambilan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delivery_courier_man_people_avatar_shipping_icon_225164.png"))); // NOI18N
        bPengambilan.setText("PENGAMBILAN");
        bPengambilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPengambilanActionPerformed(evt);
            }
        });

        bKomplain.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bKomplain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Talk-80_icon-icons.com_57266.png"))); // NOI18N
        bKomplain.setText("KOMPLAIN");
        bKomplain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKomplainActionPerformed(evt);
            }
        });

        bPelanggan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/26_122663.png"))); // NOI18N
        bPelanggan.setText("PELANGGAN");
        bPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPelangganActionPerformed(evt);
            }
        });

        bLayanan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bLayanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/female_woman_avatar_people_person_white_tone_icon_159370.png"))); // NOI18N
        bLayanan.setText("KARYAWAN");
        bLayanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLayananActionPerformed(evt);
            }
        });

        bKaryawan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bKaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/1455554374_line-24_icon-icons.com_53306.png"))); // NOI18N
        bKaryawan.setText("LAYANAN");
        bKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKaryawanActionPerformed(evt);
            }
        });

        bLaporan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/analytics_118088.png"))); // NOI18N
        bLaporan.setText("LAPORAN");
        bLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLaporanActionPerformed(evt);
            }
        });

        bKeluar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/stop_close_off_14465.png"))); // NOI18N
        bKeluar.setText("  KELUAR");
        bKeluar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BodyLayout = new javax.swing.GroupLayout(Body);
        Body.setLayout(BodyLayout);
        BodyLayout.setHorizontalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BodyLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bKomplain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bKaryawan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bKeluar)
                    .addComponent(bPengambilan)
                    .addComponent(bPelanggan)
                    .addComponent(bLayanan))
                .addGap(90, 90, 90))
        );

        BodyLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bKaryawan, bKeluar, bKomplain, bLayanan, bPelanggan, bPengambilan, bTransaksi});

        BodyLayout.setVerticalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bPengambilan))
                .addGap(18, 18, 18)
                .addGroup(BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bPelanggan)
                    .addComponent(bKomplain))
                .addGap(18, 18, 18)
                .addGroup(BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bKaryawan)
                    .addComponent(bLayanan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        BodyLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bKaryawan, bKeluar, bKomplain, bLayanan, bPelanggan, bPengambilan, bTransaksi});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Body, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTransaksiActionPerformed
        menuTransaksi();
    }//GEN-LAST:event_bTransaksiActionPerformed

    private void bPengambilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPengambilanActionPerformed
        menuPengambilan();
    }//GEN-LAST:event_bPengambilanActionPerformed

    private void bKomplainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKomplainActionPerformed
        menuKomplain();
    }//GEN-LAST:event_bKomplainActionPerformed

    private void bPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPelangganActionPerformed
        menuPelanggan();
    }//GEN-LAST:event_bPelangganActionPerformed

    private void bLayananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLayananActionPerformed
        menuKaryawan();
    }//GEN-LAST:event_bLayananActionPerformed

    private void bKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKaryawanActionPerformed
        menuLayanan();
    }//GEN-LAST:event_bKaryawanActionPerformed

    private void bKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKeluarActionPerformed
        keluar();
    }//GEN-LAST:event_bKeluarActionPerformed

    private void lExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lExitMouseClicked

    private void lMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lMinimizeMouseClicked
        this.setExtendedState(JFrame.ICONIFIED);
        
    }//GEN-LAST:event_lMinimizeMouseClicked

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_HeaderMouseDragged

    private void bLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLaporanActionPerformed
        menuLaporan();
    }//GEN-LAST:event_bLaporanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Body;
    private javax.swing.JPanel Header;
    private javax.swing.JButton bKaryawan;
    private javax.swing.JButton bKeluar;
    private javax.swing.JButton bKomplain;
    private javax.swing.JButton bLaporan;
    private javax.swing.JButton bLayanan;
    private javax.swing.JButton bPelanggan;
    private javax.swing.JButton bPengambilan;
    private javax.swing.JButton bTransaksi;
    private javax.swing.JLabel lExit;
    private javax.swing.JLabel lIconLaundry;
    private javax.swing.JLabel lMinimize;
    // End of variables declaration//GEN-END:variables
}
